
# output dir of trained models
MODEL_DIR: '../models'
# models to run
MODEL_LIST:
  - 'RandomForest'
  - 'LightGBM'
# training data file path
DATA_FILE_PATH: '../data/raw/credits.csv'
# training reports path
REPORT_DIR: '../reports'
# report figures path
FIGURES_DIR: '../reports/figures'
# number of cross-validation folds
N_CV_FOLDS: 5
# the ratio of test data set
TEST_RATIO: 0.2
# the target to be predicted
COL_LABEL: 'default payment next month'
# numberical feature names
DENSE_FEATURES:
  - 'LIMIT_BAL'
  - 'AGE'
  - 'BILL_AMT1'
  - 'PAY_AMT1'
# categorical feature names
SPARSE_FEATURES:
  - 'SEX'
  - 'EDUCATION'
  - 'MARRIAGE'
  - 'PAY_0'
  - 'PAY_2'
  - 'PAY_3'
  - 'PAY_4'
  - 'PAY_5'
  - 'PAY_6'




